#!/bin/sh

scripts/run-tests

echo "Publishing libraries to the local Maven repository..."
echo "Are we running on CI? $1"
echo "Present directory is $PWD"

# Script here...

status=$?
if [ "$status" = 0 ] ; then
    echo "Published library artifacts to the local Maven repository."
    exit 0
else
    echo 1>&2 "Publishing failed; please resolve any issues and try again."
    exit 1
fi

