name: Pull-Request Check

on:
  pull_request:
    branches: [ develop ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.RELEASE_KEY_STORE }}
        run: |
          echo $KEYSTORE_BASE64 | base64 -di > app-android-journal3/release_signing.jks

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle and SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
          RELEASE_KEY_STORE: ${{ secrets.RELEASE_KEY_STORE }}
          RELEASE_KEY_STORE_PASSWORD: ${{ secrets.RELEASE_KEY_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          RELEASE_KEY_HERE_API: ${{ secrets.RELEASE_KEY_HERE_API }}
          DEBUG_KEY_HERE_API: ${{ secrets.DEBUG_KEY_HERE_API }}
          RELEASE_KEY_OAI_API: ${{ secrets.RELEASE_KEY_OAI_API }}
          DEBUG_KEY_OAI_API: ${{ secrets.DEBUG_KEY_OAI_API }}
          RELEASE_KEY_SENTRY: ${{ secrets.RELEASE_KEY_SENTRY }}
          DEBUG_KEY_SENTRY: ${{ secrets.DEBUG_KEY_SENTRY }}
        run: ./gradlew clean build sonarqube

      - name: Archive build reports
        uses: actions/upload-artifact@v3
        with:
          name: build-report-artifacts
          path: |
            **/build/reports
